= Rapport d’avancement du groupe 5.1
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]
:doctype: book
:stem: latexmath
:source-highlighter: coderay
:toc-title: Table des matières
:toc: macro
:sectnums:
:imagesdir: images


// Partie non numérotée
:sectnums!:
== Nom du groupe : Pot'AG

=== Membres du groupe

* Andrey El-Bitar
* Aymane El Firdoussi
* Bounlhom Aphayavong
* Dário Carvalho
* Guilhem Jazeron
* Maxime Besson

=== Tuteur

* Jean Le Feuvre

=== Encadrant génie logiciel

* LINGUAGLOSSA Leonardo

== Résumé du sujet choisi en français (PAN1)

Il s’agit de créer un kit permettant de transformer une surface cultivable quelconque (potager, plante d'intérieur, jardinières de fleurs...) en surface connectée grâce à une application mobile qui permet à l'utilisateur de surveiller et modifier à distance les apports en eau, en lumière et la température des plantations. L'emploi d'un système de kit permet différents types d'usages et offre une solution évolutive (possibilité d'agrandir la surface cultivable).
////
*_Note: 15 lignes max_*

Décrire votre projet sans le scénariser : De quoi s’agit-il ? En quoi
cette idée est compatible avec le thème de PACT ? Qu’est-ce qu’il
permettrait de faire de façon générale.
////
== English Summary (PAN1)

The idea is to create a kit that transforms any cultivable surface (vegetable garden, houseplant, flower boxes etc.) into a connected surface thanks to a mobile application that enables the user to remotely monitor and manage the water, light and temperature of the plantation. The use of a kit system allows different types of uses and offers a scalable solution (possibility of enlarging the cultivabe area).
////
*_Note : 15 lignes max, version anglaise du texte précédent_*
////

////
*Notes concenant le rapport*

Les différentes pages du document sont rédigées en utilisant le langage
AsciiDoc. Le squelette de rapport contient des exemples avec entre autres:

* des images,
* des liens,
* des équations.

La structure du rapport (parties, sections et la relation avec les
différents fichiers) se trouve dans le fichier courant.

**Prenez le temps** de supprimer le texte de remplissage et les sections non
utilisées pour l'instant. Vous pouvez par exemple commenter ces parties non
utilisées pour qu'elles n'apparaissent pas dans le document final. En Asciidoc,
il suffit de les précéder de deux slashs (`//`). 
////

// en PDF on ne peut pas controler la position de la toc
// Macros non supportées
ifndef::backend-pdf[]
== Table des matières
:toc-title:
toc::[]
endif::[]

// On numérote le reste des sections
:sectnums:

== Étude d’antériorité et justification de la proposition (PAN1)

include::proposition/proposition.adoc[Description de la proposition]

include::proposition/etat-de-l-art.adoc[Description de l’état de l’art]

== Scénarios d’usage (PAN1)

include::scenario/scenario.adoc[Scénarios d’usage]

<<<

==  Architecture du projet (PAN1)


include::architecture/schema.adoc[Interface utilisateur graphique]

include::architecture/interfaces.adoc[Interface utilisateur graphique]

include::architecture/sequence.adoc[Interface utilisateur graphique]


include::architecture/ihm.adoc[Interface utilisateur graphique]

<<<

== Organisation du projet (PAN1)

include::organisation/planification.adoc[Diagramme de planification temporel des tâches]

include::organisation/plan-tests.adoc[Plans de test (PAN2+)]

<<<

[bibliography]
== Bibliographie (PAN1+)

include::References.adoc[Bibliographie]

<<<
//// 
== Annexes

include::annexes/modifications.adoc[Modifications (PAN2+)]

include::annexes/avancement.adoc[Avancement des modules]

include::annexes/moduleX.adoc[Avancement module X]

include::annexes/moduleY.adoc[Avancement module Y]
////
