=== Description de l’état de l’art
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]

*_Note : 1 page max._*

Décrivez, en les citant via la bibliographie, les approches/produits
ressemblant à votre projet et les différences éventuelles. Illustrez
avec des images si besoin. Utilisez des renvois vers votre
bibliographie : « comme démontré dans [2], … »

==== XXX

Le marché des potagers connectés s'est considérablement développé au cours de ces dernières années. En effet, de plus en plus de citadin souhaitent désormais culiver et consommer leur propre nouriture. Le principe du potager connecté est d'equiper le potager de capteur et d'actionneur afin d'assurer que les plantes puissent se développer dans des conditions optimales. Le prix des potagers connecters varient entre 60 et 250 euros. De plus, contrairement au système pot'AG, il n' est pas possible d'utiliser n'importe quelles graines, et il faut  utiliser des recharges dont le prix va de 6euros à 10 euros selon les marques. 


Le marché des potagers intéligents en France est detenu principalement par trois compagnies. La start-up Prêt à pousser propose deux modèles : Le potager Lilo, où l'on fait pousser des plantes dans trois capsules par la technique de l'hydroponie qui consiste à cultiver les plantes dans de l'eau qui contient des nutriments, et le potager Modulo qui à la diférence de Lilo s'acroche sur les murs et permet d'uliser un nombre variable de capsules. Ces deux potagers sont fourni avec une application où l'on doit rentrer l'évolution des plants et qui donne alors des conseils à chaque étape pour améliorer la récolte. Elle permet également de  modifier la luminosité gràce à des leds intégrées aux capsules. 
De son coté, Click and Grow ont developpé le potager Smart connect, doté de la technologie smart soil, qui permet de répartitr uniformément l'eau à l'interieur de la structure et de s'assurer que les plantes ont un pH parfait. Il possède aussi la technologie AdaptLight, qui permet de moduler l'intensité des LEDs d'eclairage selon la luminosité ambiante. Cependant, contrairement au Pot'AG et a Lilo, il n'est accompagné d'une application mobile. 
Le potager Connect de Veritable est le potager le plus similaire au Pot'A, il est intelligent  puisqu'il est aussi doté de la technologie AdaptLight mais est aussi connecté à une application  où l'on peut suivre l'évolution des plantes, ajuster manuelement l'éclairage et recevoir des notifications si l'on doit arroser plus les plantes.
     



==== Exemples de citations

Les références bibliographiques sont regroupées dans le fichier `References.adoc`
à la racine du répertoire `rapport`.
On peut y faire référence dans toutes les sous parties du document.

On peut citer comme exemple l'article de Claude E. Shannon sur la
théorie de la communication <<RefShannon>>
ou, bien évidement, la vitrine des projets PACT <<VitrinePACT>>.

Voir <<TOTO,la référence>> très intéressante elle aussi.
