=== Description de l’état de l’art
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]

*_Note : 1 page max._*

Décrivez, en les citant via la bibliographie, les approches/produits
ressemblant à votre projet et les différences éventuelles. Illustrez
avec des images si besoin. Utilisez des renvois vers votre
bibliographie : « comme démontré dans [2], … »

==== XXX

Le marché des potagers connectés s'est considérablement développé au cours de ces dernières années. En effet, de plus en plus de citadin souhaitent désormais culiver et consommer leur propre nouriture. Le principe du potager connecté est d'equiper le potager de capteur et d'actionneur afin d'assurer que les plantes puissent se développer dans des conditions optimales. Le prix des potagers connecters varient entre 60 et 250 euros. De plus, contrairement au système pot'AG, il n' est pas possible d'utiliser n'importe quelles graines, et il faut alors utiliser des recharges dont le prix va de 6euros à 10 euros selon les marques. 
Le marché des potagers intéligents en France est detenu principalement par trois compagnies. 

==== ZZZ

Et magnis dis parturient montes, nascetur ridiculus mus.

Aenean risus dui, volutpat non, posuere vitae, sollicitudin in, urna.
Nam eget eros a enim pulvinar rhoncus. Cum sociis natoque penatibus et
magnis dis parturient montes, nascetur ridiculus mus. Nulla facilisis
massa ut massa. Sed nisi purus, malesuada eu, porta vulputate, suscipit
auctor, nunc.

==== Exemples de citations

Les références bibliographiques sont regroupées dans le fichier `References.adoc`
à la racine du répertoire `rapport`.
On peut y faire référence dans toutes les sous parties du document.

On peut citer comme exemple l'article de Claude E. Shannon sur la
théorie de la communication <<RefShannon>>
ou, bien évidement, la vitrine des projets PACT <<VitrinePACT>>.

Voir <<TOTO,la référence>> très intéressante elle aussi.
