=== Description de l’état de l’art
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]



Le marché des potagers connectés s'est considérablement développé au cours de ces dernières années. En effet, de plus en plus de citadins souhaitent désormais cultiver et consommer leur propre nouriture. Le principe du potager connecté est d'equiper le potager de capteurs et d'actionneurs afin de s'assurer que les plantes puissent se développer dans des conditions optimales. Le prix des potagers connecters sur le marché  varie entre 60 et 250 euros <<Ref1>>. De plus, contrairement au système pot'AG, il n'est pas possible d'utiliser n'importe quelles graines, et il faut donc utiliser des recharges dont le prix va de 6 euros à 10 euros selon les marques <<Ref1>>. 


Le marché des potagers intelligents en France est détenu principalement par trois compagnies. La start-up Prêt à pousser propose deux modèles : Le potager Lilo <<Ref2>>, où l'on fait pousser des plantes dans trois capsules par la technique de l'hydroponie <<Ref3>>, qui consiste à cultiver les plantes dans de l'eau qui contient des nutriments, et le potager Modulo qui à la difference de Lilo s'accroche sur les murs et permet d'uliser un nombre variable de capsules. Ces deux potagers sont fourni avec une application où l'on doit rentrer l'évolution des plants et qui donne alors des conseils à chaque étape pour améliorer la récolte. Elle permet également de  modifier la luminosité grace à des leds intégrées aux capsules.

De son coté, Click and Grow ont developpé le potager Smart connect <<Ref5>>, doté de la technologie smart soil, qui permet de répartir uniformément l'eau à l'interieur de la structure et de s'assurer que les plantes ont un pH parfait. Il possède aussi la technologie AdaptLight, qui permet de moduler l'intensité des LEDs d'eclairage selon la luminosité ambiante. Cependant, contrairement au Pot'AG et à Lilo, il n'est pas accompagné d'une application mobile. 

Le potager Connect de Veritable <<Ref6>> est le potager le plus similaire au Pot'AG, il est intelligent puisqu'il est aussi doté de la technologie AdaptLight mais est quant à lui connecté à une application  où l'on peut suivre l'évolution des plantes, ajuster manuelement l'éclairage et recevoir des notifications si l'on doit arroser plus les plantes.
     




