=== Description des interfaces (PAN1 / PAN2)
////
Pour le PAN1, il faut identifier et décrire sommairement toutes les
interfaces entre modules.

Pour le PAN2, il faut une description complète des interfaces.

Il faut ici une description textuelle de chaque interface, c'est-à-dire chaque
échange entre deux blocs.
Si c’est une interface entre deux blocs informatiques, c’est une interface
Java.
S’il y a des échanges de données complexes, il faut en décrire le format avec
précision.
Si c’est une interface entre deux blocs électroniques, c’est une description
des signaux électroniques ou protocoles utilisés. 

////


==== Description de l'interface entre le bloc potager et le bloc cerveau (microcontroleur). 

//Description textuelle d’interface

Il est visible dans l'architecture, que le bloc potager est composé de deux sous blocs, le bloc capteurs (Température, luminosité, humidité et débit d'eau) et le bloc actionneurs (Lampes et contrôleur de débit), donc au lieu de décrire l'interface entre le bloc potager et le bloc cerveau, nous allons décrire l'interface entre chaque sous bloc et le bloc cerveau.

===== Description de l'interface entre le bloc capteurs et le bloc cerveau (microcontrôleur).

Afin d'avoir une gestion plus efficace des informations délivrées par les capteurs nous comptons utiliser des capteurs qui communiquent à l'aide du protocole I2C (Inter-Integrate Circuit) car grâce à lui nous pourront connecter un nombre raisonnable de capteurs sur le même bus. D'ailleurs il s'agit d'un protocole de communication simple à mettre en œuvre à l'aide d'un microcontrôleur, une fois que nous n'aurons qu'à gérer deux broches, la broche SDA (Serial Data) et la broche SCL (Serial Clock), donc la communication entre ces deux blocs se fera à l'aide du protocole I2C.

===== Description de l'interface entre le bloc actionneurs et le bloc cerveau (microcontrôleur).

Afin de gérer la luminosité du potager le microcontrôleur que nous utiliserons commandera les lampes grâce à une commande PWM (Pulse Width Modulation en anglais et Modulation par largeur d'impulsion en français), une fois que la PWM nous permet grâce à la variation du rapport cyclique du signal utilisé, de varier sa valeur moyenne, ce qui nous permettra de faire varier la luminosité des lampes. Pour le contrôleur de débit la commande sera faite en mode PWM ou en TOR (tout ou rien), selon le type de contrôleur de débit que nous allons utiliser. En effet, d'après nos recherches il y a des contrôleurs de débit qui sont commandés en PWM et il y en a qui sont commandés en TOR.

==== Description de l'interface entre le bloc cerveau (microcontrôleur) et le le bloc serveur.

//Description textuelle d’interface

L'échange d’informations entre le microcontrôleur et le serveur cloud se fera à l'aide d'un protocole de communication client-serveur à définir, nous avons comme choix possible le protocole HTTP, une fois qu'il est facile à mettre en œuvre sur plusieurs microcontrôleurs. Afin d'établir cette communication client-serveur, il faudra que notre microcontrôleur soit connecté sur internet, d'où la présence d'un routeur sur notre architecture.

==== Description de l'interface entre le bloc serveur et le bloc application mobile.

Comme pour le microcontrôleur, l'application mobile communiquera avec le serveur à l'aide d'un protocole de communication client-serveur sur internet.

