Mettre ici le scénario d’usage que vous avez construit lors des séances
encadrées par les experts SES. Vous pouvez mettre un scénario amélioré
(et non celui noté) si vous jugez votre scénario insuffisant pour faire
comprendre au jury PACT les différentes étapes d’utilisation de votre
produit/service ou si vous avez changé d’idées entre-temps.


==== Scénario d'usage

Marie a 35 ans, elle habite dans un appartement avec balcon, dans le 5ème arrondissement de Paris, et elle doit régulièrement partir à l'étranger pendant plusieurs jours à cause de son travail. Plusieurs de ses amies se sont mises au jardinage et produisent maintenant elles-mêmes leurs propres fraises, tomates et haricots, et ont conseillé à Marie de s'y mettre elle aussi. L'idée lui plaît, mais seulement deux questions se posent à elles : elle n'a jamais jardiné et a peur de se lancer, et ne sait pas comment gérer un potager alors qu'elle doit régulièrement s'absenter pendant plusieurs jours?
C'est alors qu'elle entend parler de Pot'AG sur une annonce en ligne : le système lui propose de gérer son potager à distance, suivre des tutoriels et recevoir des conseils personnalisés sur ses plantations, via des capteurs qu'elle placerait dans son potager. Marie décide alors de se lancer : elle acquiert sur le site de Pot'AG un boitier-interface ainsi qu'une lampe, un système d'approvisionnement en eau, un hygromètre, un capteur de luminosité et un thermomètre, tous compatibles avec le système Pot'AG.
Elle lance alors l'application fournie avec le boitier-interface, crée son compte utilisateur et renseigne son niveau. Après avoir indiqué être débutante, l'application lui dit qu'elle se situe actuellement dans la période de plantation des tomates, et lui propose un tutoriel pour lancer ses premiers pieds de tomate. Elle se rend alors sur l'onglet boutique, où sont comparés les prix des graines de tomates entre les différents revendeurs.
Elle s'empresse de commander, installe son potager et suit les instructions de l'application. Quelques jours plus tard, elle doit effectuer un déplacement professionnel de cinq jours à Tokyo, et l'application lui permet alors de surveiller et contrôler les apports en lumière et en eau de ses jeunes pousses.
De retour chez elle, il lui vient une question dont elle ne trouve pas la réponse dans l'application : qu'à cela ne tienne, elle clique sur l'onglet "Forum", pose sa question et reçoit une réponse des membres plus expérimentés qu'elle. Quelques mois plus tard, les tomates se retrouvent dans l'assiette de Marie, prêtes à être dégustées, et Marie, satisfaite de l’expérience, décide d'agrandir son potager et commande seulement de nouveaux capteurs et tuyaux pour ce faire, sans avoir à acheter tout un potager plus grand.



essai de pull/push