:nofooter:
////
Mettre ici le scénario d’usage que vous avez construit lors des séances
encadrées par les experts SES. Vous pouvez mettre un scénario amélioré
(et non celui noté) si vous jugez votre scénario insuffisant pour faire
comprendre au jury PACT les différentes étapes d’utilisation de votre
produit/service ou si vous avez changé d’idées entre-temps.
////


=== Scénario d'usage


Marie a 35 ans, elle habite dans un appartement avec balcon, dans le 5ème
arrondissement de Paris, et elle doit régulièrement partir à l'étranger pendant plusieurs jours à cause de son travail. Plusieurs de ses amies se sont mises au jardinage et produisent maintenant elles-mêmes leurs propres fraises, tomates et haricots, et ont conseillé à Marie de s'y mettre elle aussi.

L'idée plaît à Marie, mais seulement deux questions se posent à elle : elle n'a jamais jardiné et a peur de se lancer, et comment gérer un potager alors qu'elle doit régulièrement s'absenter plusieurs jours ? C'est alors qu'elle entend parler d’un kit permettant de transformer une surface quelconque en surface de culture connectée sur une annonce en ligne : le système lui propose de pouvoir gérer son potager à distance et de recevoir
des alertes sur l’état de ce dernier via des capteurs qu'elle placerait sur son potager.

Marie décide alors de se lancer : elle acquiert sur le site du projet un boîtier-interface, un spot lumineux, un système d'approvisionnement en eau, un hygromètre, un capteur de luminosité, ainsi qu'un thermomètre. Elle commence par récupérer dans son garage un vieux bac en plastique dans lequel elle dépose du terreau, puis elle lance alors l'application fournie avec le boîtier-interface, crée son compte utilisateur et renseigne le fait qu'elle compte cultiver en intérieur, pour que l'application sache qu'elle aura besoin d'une gestion de l'éclairage. Elle installe alors les capteurs en suivant les explications fournies par l’application et plante ses premières graines de fraises. Quelques jours plus tard, elle doit effectuer un déplacement professionnel de cinq jours à Tokyo, et l'application lui permet alors de surveiller les apports en lumière et en eau de ses jeunes pousses, et de les augmenter si nécessaire. 

Quelques mois plus tard, les fraises se retrouvent dans l'assiette de Marie, prêtes à être dégustées, et Marie, satisfaite de l'expérience, décide dans un premier temps d’agrandir sa surface de potager : elle commande pour cela de nouveaux un ensemble de capteurs et un boîtier-interface qu'elle installe sur son potager agrandi. Elle décide ensuite d’utiliser le même système de kit pour ses jardinières de balcon, dans lesquelles elle fait pousser des fleurs, et pour son Ficus en pot. Il lui suffit alors, comme lorsqu'elle a agrandi la surface de son potager, de commander un nouvel ensemble de capteurs et un boîtier-interface, puis grâce à l'application elle pourra suivre son ensemble de plantations, comme si c'était une seule plantation.


